
version: '3.2'
services:
  api:
    container_name:  "${APP_NAME}-api"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
    volumes:
      - .
      - ./node_modules
    ports:
      - "3333:3333"
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    container_name: "${APP_NAME}-mysql"
    image: mysql:5.7
    volumes:
      - "./data/:/var/lib/mysql"
      - "./dump/:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    networks:
      - default
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

#define network
networks:
  default:
    driver: bridge
